### PR TITLE
Interactive Python examples

### PR DESCRIPTION
**Pull request by nalgeon**
Working on #2:

- Added [codapi-js](https://github.com/nalgeon/codapi-js) dependency.
- Made Python examples interactive.

### CODE REVIEW

**Review by lmangani — APPROVED** [review]

**Comment by lmangani** [comment]
Thanks @nalgeon let me know when you want this merged and/or how to support this best 👍

**Comment by nalgeon** [comment]
I think you can merge it, everything should work fine in production.

**Comment by lmangani** [comment]
Changes are live but I see the following error:

> Either Codapi is down or there is a network failure.

Nevermind, its an example expecting a file which does not exist in the Parquet/CSV example. Should we change it to something remote?

**Comment by lmangani** [comment]
Works great on all examples w/o local file expectations:

image

**Comment by nalgeon** [comment]
My bad, fixed in #4.

**Pull request merged**
