### PR TITLE
Change Python examples to linear narrative

### PR DESCRIPTION
**Pull request by nalgeon**
Working on #2:

- Changed tabs to linear flow.
- Used examples straight from the "Trying chDB" blog post.

### CODE REVIEW

**Review by lmangani — APPROVED** [review]

**Comment by lmangani** [comment]
Fantastic! Thank you so much @nalgeon! I'll add some minor visual adjustments and perhaps an index to perfect it

**Comment by nalgeon** [comment]
Looks really nice!

**Comment by lmangani** [comment]
Yes, and really thanks to you @nalgeon 🥇

**Comment by lmangani** [comment]
PS: I think we need to make the "run" button more spectacular with some CSS magic

**Comment by nalgeon** [comment]
Thank you! 😊

> I think we need to make the "run" button more spectacular with some CSS magic

Sure! It's not styled by default, but you can customize it by setting the styles for the `codapi-toolbar button` selector. Or you can show me how you want it to look, and I'll set the styles for you (in a separate PR).

**Comment by lmangani** [comment]
I think we should promote codapi with each buttons to return your generous efforts.
Do you have any cool "Run with codapi" style or image we can use? I also added a link at the top of the page.

**Comment by lmangani** [comment]
Button style updated, check it out and let me know if you'd like it to say `Run with codapi` or any other preference

**Comment by nalgeon** [comment]
Thanks a lot, really appreciate it! There's a link to Codapi after you run the code (next to the "✓ Done" label), so I think that's enough.

**Pull request merged**
